In [7]:
import pandas as pd

# dando entrada nas tabelas que serÃ£o usadas
produtos_df = pd.read_csv(r'E:\Programas\Projetos-Python\Pandas\Contoso - Cadastro Produtos.csv', sep=';')
clientes_df = pd.read_csv(r'E:\Programas\Projetos-Python\Pandas\Contoso - Clientes.csv', sep=';')
lojas_df = pd.read_csv(r'E:\Programas\Projetos-Python\Pandas\Contoso - Lojas.csv', sep=';')
vendas2017_df = pd.read_csv(r'E:\Programas\Projetos-Python\Pandas\Contoso - Vendas  - 2017.csv', sep=';')

# filtrando as tabelas conforme as colunas que queremos
clientes_df = clientes_df[['ID Cliente', 'E-mail']]
produtos_df = produtos_df[['ID Produto', 'Nome da Marca']]
lojas_df = lojas_df[['ID Loja', 'Nome da Loja']]

# mesclando e renomeando colunas
vendas2017_df = vendas2017_df.merge(produtos_df, on='ID Produto')
vendas2017_df = vendas2017_df.merge(clientes_df, on='ID Cliente')
vendas2017_df = vendas2017_df.merge(lojas_df, on='ID Loja').rename(columns={'E-mail' : 'E-mail do Cliente'})
display(vendas2017_df)

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome da Marca,E-mail do Cliente,Nome da Loja
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,1,A. Datum,rbrumfieldmy@ameblo.jp,Loja Contoso Austin
1,640549,28/08/2017,01/09/2017,4,86,1646,3,30258,12,0,Contoso,patricia6@adventure-works.com,Loja Contoso Austin
2,102415,12/02/2017,13/02/2017,1,86,486,2,33377,4,0,Proseware,mya1@adventure-works.com,Loja Contoso Austin
3,940800,16/12/2017,22/12/2017,6,86,975,4,11108,6,0,A. Datum,meary31@desdev.cn,Loja Contoso Austin
4,715385,28/09/2017,28/09/2017,0,86,311,3,10568,6,0,Southridge Video,jphettiplaceft@utexas.edu,Loja Contoso Austin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,766546,14/10/2017,14/10/2017,0,65,346,1,7781,10,0,Fabrikam,psprowleslq@boston.com,Loja Contoso Racine No.2
980638,540137,19/07/2017,20/07/2017,1,65,397,3,30585,12,0,Wide World Importers,kathleen8@adventure-works.com,Loja Contoso Racine No.2
980639,864227,17/11/2017,17/11/2017,0,65,409,4,20491,6,0,Proseware,jscardifielddq@wp.com,Loja Contoso Racine No.2
980640,553823,24/07/2017,25/07/2017,1,65,362,3,33114,12,0,Adventure Works,evelyn1@adventure-works.com,Loja Contoso Racine No.2
980641,508546,06/07/2017,10/07/2017,4,65,338,3,20830,12,0,Fabrikam,cmollindinian5@bloglines.com,Loja Contoso Racine No.2

Acompanhar o progresso da atividade
    - from tqdm import tqdn

In [19]:
# importando a biblioteca
from tqdm import tqdm

# atribuindo uma variavel para a nossa parra de progresso
pbar = tqdm(total=len(vendas2017_df['ID Loja']), position=0, leave=True)

# percorrendo uma coluna e procurando um valor para alterar outra coluna
for i, id_loja in enumerate(vendas2017_df['ID Loja']):
    pbar.update()
    if id_loja == 86:
        vendas2017_df.loc[i, 'Quantidade Devolvida'] += 1

display(vendas2017_df)

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 980642/980642 [02:28<00:00, 6581.88it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–‰| 978674/980642 [00:02<00:00, 1891578.11it/s]

,Numero da Venda,Data da Venda,Data do Envio,ID Canal,ID Loja,ID Produto,ID Promocao,ID Cliente,Quantidade Vendida,Quantidade Devolvida,Nome da Marca,E-mail do Cliente,Nome da Loja
0,1,01/01/2017,02/01/2017,1,86,981,2,6825,9,8,A. Datum,rbrumfieldmy@ameblo.jp,Loja Contoso Austin
1,640549,28/08/2017,01/09/2017,4,86,1646,3,30258,12,7,Contoso,patricia6@adventure-works.com,Loja Contoso Austin
2,102415,12/02/2017,13/02/2017,1,86,486,2,33377,4,7,Proseware,mya1@adventure-works.com,Loja Contoso Austin
3,940800,16/12/2017,22/12/2017,6,86,975,4,11108,6,7,A. Datum,meary31@desdev.cn,Loja Contoso Austin
4,715385,28/09/2017,28/09/2017,0,86,311,3,10568,6,7,Southridge Video,jphettiplaceft@utexas.edu,Loja Contoso Austin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
980637,766546,14/10/2017,14/10/2017,0,65,346,1,7781,10,1,Fabrikam,psprowleslq@boston.com,Loja Contoso Racine No.2
980638,540137,19/07/2017,20/07/2017,1,65,397,3,30585,12,1,Wide World Importers,kathleen8@adventure-works.com,Loja Contoso Racine No.2
980639,864227,17/11/2017,17/11/2017,0,65,409,4,20491,6,1,Proseware,jscardifielddq@wp.com,Loja Contoso Racine No.2
980640,553823,24/07/2017,25/07/2017,1,65,362,3,33114,12,1,Adventure Works,evelyn1@adventure-works.com,Loja Contoso Racine No.2
980641,508546,06/07/2017,10/07/2017,4,65,338,3,20830,12,1,Fabrikam,cmollindinian5@bloglines.com,Loja Contoso Racine No.2

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 980642/980642 [00:14<00:00, 1891578.11it/s]

**Video 26 time 27:21**